### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by maxvigne** [BSData/gaslands#14]
I'd like to assist with maintaining the Gaslands data.

**Comment by amis92** [comment]
@cartag you're admin here, you can manage collaborators at https://github.com/BSData/gaslands/settings/access

I'll leave you to it, ok? :)

**Comment by maxvigne** [comment]
Hi,

Thanks, I’ll go from here.

Cheers,
Max

Sent from my iPad

On 16 Mar 2020, at 8:04 pm, Amadeusz Sadowski <notifications@github.com> wrote:

﻿

@cartag<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcartag&data=02%7C01%7C%7C91baf7d7d47847d98edc08d7c9890a18%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637199462720304566&sdata=xKLL0PCbh7Sb0WW7Mt1vIZ51ztgKLVk%2B01awdV1S5%2BM%3D&reserved=0> you're admin here, you can manage collaborators at https://github.com/BSData/gaslands/settings/access<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBSData%2Fgaslands%2Fsettings%2Faccess&data=02%7C01%7C%7C91baf7d7d47847d98edc08d7c9890a18%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637199462720314560&sdata=S2UTScLS%2FrUAmtxYDwOIfDiFEGdg%2FLaSbfcjdR9weIs%3D&reserved=0>

I'll leave you to it, ok? :)

**Comment by cartag** [comment]
Invite has been sent. I got it @amis92 :)
