### ISSUE TITLE
Refuelled Updates 

### ISSUE THREAD

**Issue by MountyChris** [BSData/gaslands#7]
Hope this helps. Complete list of list changes for Refuelled 

VEHICLES 
- [x] Remove jeep
- [x] Remove apc 
- [x] Remove trike
- [x] Remove coach
- [x] Remove motor home
- [x] Remove van/ tractor 

- [x] Ice cream truck handling 3 》 2
- [x] Ice cream truck cans 5 》 8
- [x] Buggy cans 5 》 6
- [x] Helecopter crew 2》3
- [x] Ambulance cans 25》20

- [x] Tank, new rule, Turret, one weapon may be turret mounted for free. 
- [x] Helecopter & tank new rule, Restricted 
- 
UPGRADES 
- [x] Remove ejector seat 
- [x] Remove cluster bombs
- [x] Improvised sludge thrower cans 1》2 
- [x] Add Experimental Nuclear Engine 5 cans 0 build slots 
- [x] Add Experimental teleporter 7 cans, 0 build slots 
- [x] Add roll cage 4 cans 1 build slot 

- [x] Exploding ram build slots 1 》 0

WEAPONS 
- [x] Remove homing missile
- [x] Remove hypno ray
- [x] Remove rifle 

- [x] Add Bazooka, 4 cans, 2 build slots 
- [x] Add Magnum,  3 cans (crew fired)
- [x] Add Napalm dropper, 1 can 1 build slot (dropped) 
- [x] Add Wall of Amplifiers, 4 cans , 3 build slots , 360 arc
- [x] Blunderbuss, buildslots 1》0, crew fired 

- [x] Minigun cost 6》5
- [x] Heavy Machine gun cost 4 》3
- [x] RC bomb cost 6》3
- [x] Rockets cost 5》4
- [x] Sentry gun cost 2 》3
- [x] Shotgun cost 4》3
- [x] Steel nets cost 1》2
- [x] Submachine gun cost 6》5

SPONSORS

- [x] Slime, lose aggression and speed.
- [x] Gain tuning and reckless 
- [x] New rule, Spiked Fist, Rams have 0 build slots for slime teams

- [x] New Sponsor Verney
- [x] Technology and Built 
- [x] Unique upgrade, MicroPlate Armour, 6 cans, 0 build slots, increases hull by 2.

- [x] New Sponsor Maxxine
- [x] Tuning and Pursuit 

- [x] New Sponsor The Order of the Inferno
- [x] Horror and Speed

- [x] New Sponsor Beverly, The Devil On The Highway
- [x] Horror and Built 

- [x] New Sponsor Rusty's Bootleggers 
- [x] Reckless and Built 
- [x] Unique upgrade Trailers (adds build slots to vehicle) 
- [x] At least one must be taken, or a War Rig. 
- [x] Trailer (Lightweight). Additional Build Slots 0, 4 cans
- [x] Trailer (Middlewieght), additional build slots 1, 8 cans (middleweight and Heavyweight only)
- [x] Trailer (Heavyweight), additional build slots 3, cost 12

Each trailer or war rig may take one free upgrade from this list.
- [x] Peach Moonshine 
- [x] Sourmash Jet Booster 
- [x] Siphon Pump
- [x] Old Fashioned Corn Liquor
- [x] Cattle-hammer 

PERKS 

Badass 
- [x] Remove Fist of Steel 
- [x] Add Bullet-time, 3 cans 

Daring
- [x] Remove Trick Driving
- [x] Add Hand Brake Artist, 3 cans 

Precision
- [x] Remove Big Tires 
- [x] Remove Handbrake Artist 
- [x] Add Mister Fahrenheit, 2 cans
- [x] Add Trick Driving, 3 cans 

Technology 
- [x] Remove Experimental Nuclear Engine
- [x] Remove Experimental Teleporter 
- [x] Add Satellite Navigation, 2 cans  
- [x] Add Eureka!, 4 cans 

New Perk class: Built 
- [x] Dead Weight, 2 cans
- [x] Barrel Roll, 2 cans
- [x] Bruiser, 4 cans 
- [x] Splashback, 5 cans 
- [x] Crusher, 7 cans 
- [x] Feel No Pain, 8 cans 

New Perk class: Horror 
- [x] Purifying Flames, 1 can
- [x] Ecstatic Visions, 1 can
- [x] Sympathy for the Devil, 1 can 
- [x] Highway to Hell, 2 cans
- [x] Violent Manifestation, 3 cans 
- [x] Angel of Death, 4 cans

New Perk Class: Reckless 
- [x] Drive Angry, 1 can 
- [x] Hog wild, 2 cans 
- [x] In for a Penny , 2 cans
- [x] Don't Come Knocking, 4 cans 
- [x] Bigger'N You, 4 cans 
- [x] Beerserker, 5 cans

**Comment by MountyChris** [comment]
Flamethrower is now 4 cans 

The turret cost multiplier seems to have stopped working.

**Comment by cartag** [comment]
Turret cost doesn't actually triple it in the software, it sets the value to something 3x higher. When the Flamethrower was 6 points, it cost 18 on the turret, that's why. It was hard set to 18.

**Comment by NeoDaitou** [comment]
The Wall of Amplifiers weapon is not available for selection and is listed as hidden in the gst file.
