### ISSUE TITLE
Gaslands [Join Request]

### ISSUE THREAD

**Issue by P1TBEAST** [BSData/gaslands#8]
Saw on a /r/battlescribe thread that the gaslands repo is not currently being updated. Would like to review and update.

I have limited exposure to XML through work (can read and make minor changes, but not currently skilled enough to start from scratch).

I'd love to help in any way possible.

**Comment by cartag** [comment]
Paging @amis92

**Comment by amis92** [comment]
Hello, @P1TBEAST. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData/gaslands/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide

**Comment by amis92** [comment]
Invitation timed out. Please re-request if you're still interested.
