### ISSUE TITLE
Wall of Amplifiers - Refuelled Update

### ISSUE THREAD

**Issue by NeoDaitou** [BSData/gaslands#9]
I commented on the Refuelled Updates, but I'm not sure if that gets seen once the issue is closed.  The Wall of Amplifiers weapon is not available for selection in BattleScribe.  I checked the gst file and it's listed in there, but tagged as hidden.  Can we get that opened up or is it hidden for a reason right now?

**Comment by cartag** [comment]
It was a bug, I've resolved it.
